### ISSUE TITLE
Bump all deps

### ISSUE THREAD

**Issue by Milo123459** [cometkim/yarn-plugin-bump#14]
Hi, so when running `yarn bump` - it bump's all deps in package.json, can we make it so it bumps deps that other deps require on?

ie, @types/mongoose requires on @types/mongodb

Let's say @types/mongodb is out date, so, running yarn bump updates @types/mongodb, and any deps of @types/mongodb that are out date also get updated, and vice verse

Maybe this could be an option like -r for recursive?

**Comment by Milo123459** [comment]
@cometkim Any news? 👀

**Comment by cometkim** [comment]
hey @Milo123459, thank you for the suggestion.

Since this is a very rarely used plugin to me, I'm not planning on it right now, but it seems like a good suggestion. I will try probably in the end of this month.

BTW I'm sad that alternatives like Renovate or Dependabot are not yet ready (not completely, but renovate seems to almost there).

Could you tell me how and why you use this plugin instead of the [interactive one](https://github.com/yarnpkg/berry/blob/master/packages/plugin-interactive-tools/README.md) so might motivate me :eyes:

**Comment by Milo123459** [comment]
I use this plugin because it's easy, one command, all dependencies updated, I don't need to manually select things, and it is purely an amazing tool. Also, I use the command almost every day for my projects, right now to fix my issue I need to delete .pnp.js, yarn.lock, .yarn/cache, .yarn/unplugged, .yarn/build-state.yml and .yarn/install-state.gz

But well done, it's an amazing plugin. All my yarn v2 projects use it!

Looking forward to the end of the month!

**Comment by Milo123459** [comment]
@cometkim How's it going?

**Comment by Milo123459** [comment]
BTW, I made a pr to https://github.com/Samantha-uk/awesome-yarn adding yarn bump as an awesome plugin!

More motivation :)

**Comment by Milo123459** [comment]
@cometkim Sorry if I'm being annoying, but, is there any progress..?

**Comment by cometkim** [comment]
@Milo123459 Sorry for the late response. I have been resting for several weeks.

This plugin relies on essential plugins (built-in commands) instead of manipulating lock files directly. And this is the default behavior of the `up` command... But I think this can be done by changing behavior, with a little parsing,  the `add` command, and hacking some internal utilities.

It needs poc and since I have several projects with priority, It's not right now, but I'll ping you when the experiment is done. It won't take that long.

**Comment by Milo123459** [comment]
Looking forward to it.

**Comment by Milo123459** [comment]
Still no eta?

**Comment by Milo123459** [comment]
https://github.com/yarnpkg/berry/pull/2427 might help
